# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gen_code1.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogTwo(object):
    def setupUi(self, DialogTwo):
        DialogTwo.setObjectName("DialogTwo")
        DialogTwo.resize(431, 532)
        font = QtGui.QFont()
        font.setPointSize(12)
        DialogTwo.setFont(font)
        self.pushButton = QtWidgets.QPushButton(DialogTwo)
        self.pushButton.setGeometry(QtCore.QRect(320, 470, 71, 31))
        self.pushButton.setObjectName("pushButton")
        self.textEdit = QtWidgets.QTextEdit(DialogTwo)
        self.textEdit.setGeometry(QtCore.QRect(40, 40, 351, 401))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.textEdit.setFont(font)
        self.textEdit.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.textEdit.setObjectName("textEdit")

        self.retranslateUi(DialogTwo)
        QtCore.QMetaObject.connectSlotsByName(DialogTwo)

    def retranslateUi(self, DialogTwo):
        _translate = QtCore.QCoreApplication.translate
        DialogTwo.setWindowTitle(_translate("DialogTwo", "Dialog"))
        self.pushButton.setText(_translate("DialogTwo", "ОК"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogTwo = QtWidgets.QDialog()
    ui = Ui_DialogTwo()
    ui.setupUi(DialogTwo)
    DialogTwo.show()
    sys.exit(app.exec_())
